# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :nginx => {
    :box_name => "redos732"
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      # Удалите строку с конкретным IP-адресом
      # Используйте стандартный private_network, если это возможно
      box.vm.network "private_network", type: "dhcp"
      box.vm.provider "vmware_desktop" do |v|
        v.vmx["memsize"] = "1024" # Установка памяти в MB
      end
    end
  end
end

