# -*- mode: ruby -*-
# vim: set ft=ruby :
MACHINES = {
  :consul1 => {
        :box_name => "redos732",
        :ip_addr => '192.168.56.191'
  },
  :consul2 => {
        :box_name => "redos732",
        :ip_addr => '192.168.56.192'
  },
  :consul3 => {
        :box_name => "redos732",
        :ip_addr => '192.168.56.193'
  },  
  :nfs => {
      :box_name => "redos732",
      :ip_addr => '192.168.56.188'
  },
  :pg1 => {
        :box_name => "redos732",
        :ip_addr => '192.168.56.181'
  },
  :pg2 => {
        :box_name => "redos732",
        :ip_addr => '192.168.56.182'
  }

}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s
        box.vm.network "private_network", type: "dhcp"
        box.vm.provider "vmware_desktop" do |vb|
          vb.vmx["memory"] = "1024"
        end
        case boxname.to_s
            when "pg1"
                  box.vm.disk :disk, size: "10GB", name: "pg1_data"
                  box.vm.disk :disk, size: "1GB", name: "pg1_wal"
            when "pg2"
                  box.vm.disk :disk, size: "10GB", name: "pg2_data"
                  box.vm.disk :disk, size: "1GB", name: "pg2_wal"
            when "nfs"
                  box.vm.disk :disk, size: "10GB", name: "nfs_backup"
        end
        ssh_pub_key = File.readlines("/Users/dimagic/.ssh/redos732.pub").first.strip
        config.vm.provision "shell" do |s|
            s.inline = <<-SHELL
                  mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
                  sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
                  echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
                  echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
                  # systemctl restart sshd
            SHELL
        end
    end
  end
end
