---
- name: Setup hosts
  hosts: all
  become: true
  roles: 
    - selinux
    - nginx
- name: Setup webservers
  hosts: webservers
  become: true
  roles: 
    - webserver
- name: Setup balancer
  hosts: balancer
  become: true
  roles: 
    - balancer
