version: '3.1'
services:
  nginx:
   image: conty111/my-conty-nginx:latest
   container_name: nginx
   ports:
     - "8080:80"
   volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  php:
   image: conty111/my-conty-php-info:latest
   container_name: php
  #  ports:
  #    - "9000:9000"